MovieCore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from MovieCore import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.urls import path

from catalog.views import (
    index,
    GenreListView,
    MovieListView,
    ActorListView,
    DirectorListView,
    ActorDetailView,
    MovieDetailView,
    DirectorDetailView,
    GenreDetailView,
    no_license_view,
    MovieCreateView,
    DirectorUpdateView,
    RegisterDirectorView,
    ActorCreateView,
    MovieUpdateView,
    GenreCreateView,
    GenreDeleteView,
    ActorDeleteView,
    MovieDeleteView,
    DirectorDeleteView, ToggleDirectorView,
)

urlpatterns = [
    path("", index, name="index"),
    path("register/", RegisterDirectorView.as_view(), name="register_director"),
    path("no-license/", no_license_view, name="no_license"),
    # Genres
    path("genres/", GenreListView.as_view(), name="genre_list"),
    path("genres/<int:pk>/", GenreDetailView.as_view(), name="genre_detail"),
    path("genres/create/", GenreCreateView.as_view(), name="genre_create"),
    path("genres/<int:pk>/delete/", GenreDeleteView.as_view(), name="genre_delete"),
    # Movies
    path("movies/", MovieListView.as_view(), name="movie_list"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie_detail"),
    path(
        "movies/<int:pk>/toggle-director/",
        ToggleDirectorView.as_view(),
        name="toggle_director"),
    path("movies/<int:pk>/update/", MovieUpdateView.as_view(), name="movie_update"),
    path("movies/<int:pk>/delete/", MovieDeleteView.as_view(), name="movie_delete"),
    path("movies/create/", MovieCreateView.as_view(), name="movie_create"),
    # Actors
    path("actors/", ActorListView.as_view(), name="actor_list"),
    path("actors/<int:pk>/", ActorDetailView.as_view(), name="actor_detail"),
    path("actors/create/", ActorCreateView.as_view(), name="actor_create"),
    path("actors/<int:pk>/delete/", ActorDeleteView.as_view(), name="actor_delete"),
    # Directors
    path("directors/", DirectorListView.as_view(), name="director_list"),
    path("directors/<int:pk>/", DirectorDetailView.as_view(), name="director_detail"),
    path(
        "directors/<int:pk>/update/",
        DirectorUpdateView.as_view(),
        name="director_update",
    ),
    path(
        "directors/<int:pk>/delete/",
        DirectorDeleteView.as_view(),
        name="director_delete",
    ),
]

app_name = "catalog"

templates/includes/footer.html
<footer class="bg-dark text-light text-center py-3 mt-auto">
  <div class="container">
    <p class="mb-0">© 2025 MovieCore. Yevhen Nastoiashchyi. Done in the learning process.
    </p>
  </div>
</footer>

templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3">
  <a class="navbar-brand" href="{% url 'catalog:index' %}">🎬MovieCore</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto">
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'movie_list' %}active{% endif %}" href="{% url 'catalog:movie_list' %}">Movies</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'actor_list' %}active{% endif %}" href="{% url 'catalog:actor_list' %}">Actores</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'director_list' %}active{% endif %}" href="{% url 'catalog:director_list' %}">Directores</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'genre_list' %}active{% endif %}" href="{% url 'catalog:genre_list' %}">Genres</a>
      </li>
    </ul>

    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ user.get_absolute_url }}">{{ user.first_name }} {{ user.last_name }} </a>
        </li>

        <li class="nav-item">
          <form method="post" action="{% url 'logout' %}" style="display: inline;">
          {% csrf_token %}
          <button type="submit" class="btn btn-link nav-link">Logout</button>
          </form>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
      {% endif %}
    </ul>

  </div>
</nav>

templates/includes/pagination.html
{% if is_paginated %}
  <nav aria-label="Pages">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1{% if search_query %}&q={{ search_query }}{% endif %}">« First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}">‹ Back</a>
        </li>
      {% endif %}

      <li class="page-item disabled">
        <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
      </li>

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}">Forward ›</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if search_query %}&q={{ search_query }}{% endif %}">Last »</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}